RAND_RAN_NUM = 0

READ_PAR = False

TICK_SUM = 0
TICK_MAX = 500
AI_INPUT_SHAPE = 13
AI_MIDDLE_SHAPE = 16
AI_OUTPUT_SHAPE = 9

LENGTH_CHROM = 409
LOW = -1.0
UP = 1.0
ETA = 20

# константы генетического алгоритма
POPULATION_SIZE = 20   # количество индивидуумов в популяции
P_CROSSOVER = 0.9       # вероятность скрещивания
P_MUTATION = 0.1        # вероятность мутации индивидуума
MAX_GENERATIONS = 5000    # максимальное количество поколений
HALL_OF_FAME_SIZE = 2

MAX_SPEED = 12.0
MAX_SPEED_ROT = 3.0
ACCELERATION_RATE_START = 0.4
ACCELERATION_RATE_STOP = 0.4
ACCELERATION_RATE_ROT = 1.6
ENGINEFORCE = 1600000
BRAKINGFORCE = ENGINEFORCE / 10
C_DRAG = 0.7
C_RR = 3000
MASS = 900
WHEEL_ROT_PER_SEC = 0.5 * 60
WHEEL_ROT_MAX = 5

COUNT_CARS = 8
CAR_START_X = 250
CAR_START_Y = 830.

GEN = 1

SCREEN_WIDTH = 1800
SCREEN_HEIGHT = 900
SCREEN_TITLE = "CAR_AI"
